bot:
    key: 7560315511:AAGJyaNacSDNXX0tcz2UKUAq5zk67zTmQr0
    name: Webster onboarding
spring:
    application:
        name: telegram-bot
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://ash-fairy-4221.j77.aws-ap-southeast-1.cockroachlabs.cloud:26257/postgres
        username: khabib
        password: dG-cxrUq2a0m_Xr3r3uO6A
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true